services:
  - type: web
    name: firstclass-ai-video-clipper
    env: docker
    plan: starter
    numInstances: 1
    region: oregon
    dockerfilePath: clipyr/Dockerfile
    healthCheckPath: /
    autoDeploy: false
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: GRADIO_SERVER_NAME
        value: "0.0.0.0"
      - key: GRADIO_SERVER_PORT
        value: "7860"
